development:
  adapter: mysql2
  database: blogapp_development
  username: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: blogapp
  username: admin
  host: blogapp.csudrfkkycq3.us-west-2.rds.amazonaws.com
  password: Tlqkfsja1
  port: 3306
  pool: 5
  timeout: 5000